# Use an official Node.js runtime as a parent image
FROM node:18-alpine
# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./
# Install application dependencies
RUN npm install
# Copy the rest of the application code to the working directory
COPY . .

# Expose the port your app will run on
EXPOSE 1337

# Define the command to run your application (modify as needed)
CMD npm run start